[[phrases]]
ipros = "ğŸ‘"

[[phrases]]
icons = "ğŸ‘"

[[phrases]]
ilink = "ğŸ”—"

[[phrases]]
ilink = "â›“ï¸"

[[phrases]]
ianchor = "âš“"

[[phrases]]
inote = "ğŸ—’ï¸"

[[phrases]]
imemo = "ğŸ“"

[[phrases]]
ifolder = "ğŸ“"

[[phrases]]
ipage = "ğŸ“„"

[[phrases]]
imouse = "ğŸ–±ï¸"

[[phrases]]
istick = "ğŸ•¹ï¸"

[[phrases]]
ichestnut = "ğŸŒ°"

[[phrases]]
itag = "ğŸ·ï¸"

[[phrases]]
ibookmark = "ğŸ”–"

[[phrases]]
ibox = "ğŸ”²"

[[phrases]]
ibox = "ğŸ”˜"

[[phrases]]
iok = "âœ”ï¸"

[[phrases]]
iok = "âœ…"

[[phrases]]
iok = "â­•"

[[phrases]]
iko = "âŒ"

[[phrases]]
iko = "â"

[[phrases]]
iplus = "â•"

[[phrases]]
iminus = "â–"

[[phrases]]
itimes = "âœ–ï¸"

[[phrases]]
idiv = "â—"
