[[phrases]]
iapple = "ï£¿"

[[phrases]]
icut = "âœ„"

[[phrases]]
ibox = "â˜"

[[phrases]]
iok = "âœ“"

[[phrases]]
iok = "âœ”"

[[phrases]]
iok = "ğŸ—¸"

[[phrases]]
iok = "â˜‘"

[[phrases]]
iok = "ğŸ—¹"

[[phrases]]
iko = "âœ•"

[[phrases]]
iko = "âœ–"

[[phrases]]
iko = "âœ—"

[[phrases]]
iko = "âœ˜"

[[phrases]]
iko = "ğŸ—´"

[[phrases]]
iko = "ğŸ—¶"

[[phrases]]
iko = "â˜’"

[[phrases]]
iko = "â®½"

[[phrases]]
iko = "ğŸ—µ"

[[phrases]]
iko = "ğŸ—·"

[[phrases]]
ibar = "ï½œ"

[[phrases]]
idot = "Â·"

[[phrases]]
idot = "â‹®"

[[phrases]]
isquare = "â–¢"

[[phrases]]
icircle = "â—¯"

[[phrases]]
itriangle = "ğŸ›†"

[[phrases]]
icross = "ğŸ—™"

[[phrases]]
imale = "â™‚"

[[phrases]]
ifemale = "â™€"

[[phrases]]
icopr = "Â©"

[[phrases]]
ireg = "Â®"

[[phrases]]
iphono = "â“…"

[[phrases]]
itel = "â„¡"

[[phrases]]
itm = "â„¢"

[[phrases]]
ism = "â„ "

[[phrases]]
idagger = "â€ "

[[phrases]]
idegree = "Â°"

[[phrases]]
ilove = "â¤"

[[phrases]]
imusic = "â™ª"

[[phrases]]
imusic = "â™¬"

[[phrases]]
ipara = "Â¶"

[[phrases]]
isect = "Â§"

[[phrases]]
iparty = "â˜­"

[[phrases]]
istar = "â˜…"

[[phrases]]
istar = "â˜†"

[[phrases]]
itaichi = "â˜¯"

[[phrases]]
izkh = "ã€Œ"

[[phrases]]
izkh = "ã€"

[[phrases]]
izkh = "ã€–"

[[phrases]]
izkh = "ã€”"

[[phrases]]
izkh = "â½"

[[phrases]]
izkh = "â‚"

[[phrases]]
izkh = "ğŸ—¦"

[[phrases]]
iykh = "ã€"

[[phrases]]
iykh = "ã€"

[[phrases]]
iykh = "ã€—"

[[phrases]]
iykh = "ã€•"

[[phrases]]
iykh = "â¾"

[[phrases]]
iykh = "â‚"

[[phrases]]
iykh = "ğŸ—§"

[[phrases]]
isharp = "â™¯"

[[phrases]]
iflat = "â™­"

[[phrases]]
irmb = "Â¥"

[[phrases]]
idc = "â“"

[[phrases]]
iprime = "â€²"

[[phrases]]
iprime = "â€³"

[[phrases]]
iprime = "â€´"

[[phrases]]
iprime = "â—"
