[[phrases]]
ipros = "ğŸ‘"

[[phrases]]
icons = "ğŸ‘"

[[phrases]]
ilink = "ğŸ”—"

[[phrases]]
ilink = "â›“ï¸"

[[phrases]]
ianchor = "âš“"

[[phrases]]
inote = "ğŸ—’ï¸"

[[phrases]]
imemo = "ğŸ“"

[[phrases]]
ifolder = "ğŸ“"

[[phrases]]
ipage = "ğŸ“„"

[[phrases]]
imouse = "ğŸ–±ï¸"

[[phrases]]
istick = "ğŸ•¹ï¸"

[[phrases]]
igame = "ğŸ®"

[[phrases]]
ichestnut = "ğŸŒ°"

[[phrases]]
itag = "ğŸ·ï¸"

[[phrases]]
ibookmark = "ğŸ”–"

[[phrases]]
ibox = "ğŸ”²"

[[phrases]]
ibox = "ğŸ”˜"

[[phrases]]
iok = "ğŸ†—"  # Squared Ok

[[phrases]]
iko = "ğŸ†–"  # Squared Ng

[[phrases]]
iok = "ğŸ‰‘"  # Approved

[[phrases]]
iko = "ğŸˆ²"  # Prohibited

[[phrases]]
iok = "âœ…"  # White Heavy Check Mark 2010

[[phrases]]
iko = "âŒ"  # Cross Mark

[[phrases]]
iplus = "â•"

[[phrases]]
iminus = "â–"

[[phrases]]
itimes = "âœ–ï¸"

[[phrases]]
idiv = "â—"
