[[phrases]]
ishift = "⇧"

[[phrases]]
ictrl = "⌃"

[[phrases]]
iopt = "⌥"

[[phrases]]
icmd = "⌘"

[[phrases]]
iesc = "⎋"

[[phrases]]
iesc = "␛"

[[phrases]]
icaps = "⇪"

[[phrases]]
idel = "⌫"

[[phrases]]
iret = "↩︎"

[[phrases]]
ispace = "␣"

[[phrases]]
itab = "⇥"
