[[phrases]]
iapple = "ï£¿"

[[phrases]]
icut = "âœ„"

[[phrases]]
ibox = "â˜"

[[phrases]]
iok = "âœ“"  # Check Mark

[[phrases]]
iko = "âœ—"  # Ballot X

[[phrases]]
iok = "â˜‘"  # Ballot Box with Check

[[phrases]]
iko = "â˜’"  # Ballot Box with X

[[phrases]]
iempty = "âˆ…"

[[phrases]]
ibar = "ï½œ"

[[phrases]]
idot = "ãƒ»"

[[phrases]]
iquote = "ï½€"  # Fullwidth

[[phrases]]
iquote = "â€²"  # Prime: feet, minutes

[[phrases]]
iquote = "â€³"  # Double Prime: inches, seconds

[[phrases]]
isquare = "â–¢"

[[phrases]]
isquare = "â¬š"

[[phrases]]
icircle = "â—¯"

[[phrases]]
itriangle = "âŸ"

[[phrases]]
icross = "â›Œ"

[[phrases]]
imale = "â™‚"

[[phrases]]
ifemale = "â™€"

[[phrases]]
icopr = "Â©"

[[phrases]]
ireg = "Â®"

[[phrases]]
iphono = "â“…"

[[phrases]]
itel = "â„¡"

[[phrases]]
itm = "â„¢"

[[phrases]]
ism = "â„ "

[[phrases]]
idagger = "â€ "

[[phrases]]
ideg = "Â°"

[[phrases]]
ilove = "â¤"

[[phrases]]
imusic = "â™ª"

[[phrases]]
imusic = "â™¬"

[[phrases]]
ipara = "Â¶"

[[phrases]]
isect = "Â§"

[[phrases]]
iparty = "â˜­"

[[phrases]]
istar = "â˜…"

[[phrases]]
istar = "â˜†"

[[phrases]]
itaichi = "â˜¯"

[[phrases]]
izkh = "ã€Œ"

[[phrases]]
izkh = "ã€"

[[phrases]]
izkh = "ã€–"

[[phrases]]
izkh = "ã€”"

[[phrases]]
izkh = "â½"

[[phrases]]
izkh = "â‚"

[[phrases]]
iykh = "ã€"

[[phrases]]
iykh = "ã€"

[[phrases]]
iykh = "ã€—"

[[phrases]]
iykh = "ã€•"

[[phrases]]
iykh = "â¾"

[[phrases]]
iykh = "â‚"

[[phrases]]
isharp = "â™¯"

[[phrases]]
iflat = "â™­"

[[phrases]]
iclef = "ğ„"

[[phrases]]
irmb = "Â¥"

[[phrases]]
idc = "â“"

[[phrases]]
islash = "ï¼"
