# small chars
[[phrases]]
iva = "áµƒ"

[[phrases]]
iva = "â‚"

[[phrases]]
ivb = "áµ‡"

[[phrases]]
ivc = "á¶œ"

[[phrases]]
ivd = "áµˆ"

[[phrases]]
ive = "â‚‘"

[[phrases]]
ive = "áµ‰"

[[phrases]]
ive = "â‚”"

[[phrases]]
ivf = "á¶ "

[[phrases]]
ivg = "áµ"

[[phrases]]
ivh = "Ê°"

[[phrases]]
ivh = "â‚•"

[[phrases]]
ivi = "áµ¢"

[[phrases]]
ivi = "â±"

[[phrases]]
ivi = "áµ"

[[phrases]]
ivj = "Ê²"

[[phrases]]
ivj = "â±¼"

[[phrases]]
ivk = "áµ"

[[phrases]]
ivk = "â‚–"

[[phrases]]
ivl = "Ë¡"

[[phrases]]
ivl = "â‚—"

[[phrases]]
ivm = "áµ"

[[phrases]]
ivm = "â‚˜"

[[phrases]]
ivn = "â¿"

[[phrases]]
ivn = "â‚™"

[[phrases]]
ivo = "áµ’"

[[phrases]]
ivo = "â‚’"

[[phrases]]
ivp = "áµ–"

[[phrases]]
ivp = "â‚š"

[[phrases]]
ivr = "Ê³"

[[phrases]]
ivr = "áµ£"

[[phrases]]
ivs = "Ë¢"

[[phrases]]
ivs = "â‚›"

[[phrases]]
ivt = "áµ—"

[[phrases]]
ivt = "â‚œ"

[[phrases]]
ivu = "áµ˜"

[[phrases]]
ivu = "áµ¤"

[[phrases]]
ivv = "áµ›"

[[phrases]]
ivv = "áµ¥"

[[phrases]]
ivw = "Ê·"

[[phrases]]
ivx = "Ë£"

[[phrases]]
ivx = "â‚“"

[[phrases]]
ivy = "Ê¸"

[[phrases]]
ivz = "á¶»"

# Tones
[[phrases]]
iva = "Ä"

[[phrases]]
iva = "Ã¡"

[[phrases]]
iva = "Ç"

[[phrases]]
iva = "Ã "

[[phrases]]
ive = "Ä“"

[[phrases]]
ive = "Ã©"

[[phrases]]
ive = "Ä›"

[[phrases]]
ive = "Ã¨"

[[phrases]]
ivi = "Ä«"

[[phrases]]
ivi = "Ã­"

[[phrases]]
ivi = "Ç"

[[phrases]]
ivi = "Ã¬"

[[phrases]]
ivo = "Å"

[[phrases]]
ivo = "Ã³"

[[phrases]]
ivo = "Ç’"

[[phrases]]
ivo = "Ã²"

[[phrases]]
ivu = "Å«"

[[phrases]]
ivu = "Ãº"

[[phrases]]
ivu = "Ç”"

[[phrases]]
ivu = "Ã¹"

# Mathematical Sans-Serif Bold Italic
[[phrases]]
iva = "ğ˜¼"

[[phrases]]
ivb = "ğ˜½"

[[phrases]]
ivc = "ğ˜¾"

[[phrases]]
ivd = "ğ˜¿"

[[phrases]]
ive = "ğ™€"

[[phrases]]
ivf = "ğ™"

[[phrases]]
ivg = "ğ™‚"

[[phrases]]
ivh = "ğ™ƒ"

[[phrases]]
ivi = "ğ™„"

[[phrases]]
ivj = "ğ™…"

[[phrases]]
ivk = "ğ™†"

[[phrases]]
ivl = "ğ™‡"

[[phrases]]
ivm = "ğ™ˆ"

[[phrases]]
ivn = "ğ™‰"

[[phrases]]
ivo = "ğ™Š"

[[phrases]]
ivp = "ğ™‹"

[[phrases]]
ivq = "ğ™Œ"

[[phrases]]
ivr = "ğ™"

[[phrases]]
ivs = "ğ™"

[[phrases]]
ivt = "ğ™"

[[phrases]]
ivu = "ğ™"

[[phrases]]
ivv = "ğ™‘"

[[phrases]]
ivw = "ğ™’"

[[phrases]]
ivx = "ğ™“"

[[phrases]]
ivy = "ğ™”"

[[phrases]]
ivz = "ğ™•"

[[phrases]]
iva = "ğ™–"

[[phrases]]
ivb = "ğ™—"

[[phrases]]
ivc = "ğ™˜"

[[phrases]]
ivd = "ğ™™"

[[phrases]]
ive = "ğ™š"

[[phrases]]
ivf = "ğ™›"

[[phrases]]
ivg = "ğ™œ"

[[phrases]]
ivh = "ğ™"

[[phrases]]
ivi = "ğ™"

[[phrases]]
ivj = "ğ™Ÿ"

[[phrases]]
ivk = "ğ™ "

[[phrases]]
ivl = "ğ™¡"

[[phrases]]
ivm = "ğ™¢"

[[phrases]]
ivn = "ğ™£"

[[phrases]]
ivo = "ğ™¤"

[[phrases]]
ivp = "ğ™¥"

[[phrases]]
ivq = "ğ™¦"

[[phrases]]
ivr = "ğ™§"

[[phrases]]
ivs = "ğ™¨"

[[phrases]]
ivt = "ğ™©"

[[phrases]]
ivu = "ğ™ª"

[[phrases]]
ivv = "ğ™«"

[[phrases]]
ivw = "ğ™¬"

[[phrases]]
ivx = "ğ™­"

[[phrases]]
ivy = "ğ™®"

[[phrases]]
ivz = "ğ™¯"

# Mathematical Script
[[phrases]]
iva = "ğ’œ"

[[phrases]]
ivb = "â„¬"

[[phrases]]
ivc = "ğ’"

[[phrases]]
ivd = "ğ’Ÿ"

[[phrases]]
ive = "â„°"

[[phrases]]
ivf = "â„±"

[[phrases]]
ivg = "ğ’¢"

[[phrases]]
ivh = "â„‹"

[[phrases]]
ivi = "â„"

[[phrases]]
ivj = "ğ’¥"

[[phrases]]
ivk = "ğ’¦"

[[phrases]]
ivl = "â„’"

[[phrases]]
ivm = "â„³"

[[phrases]]
ivn = "ğ’©"

[[phrases]]
ivo = "ğ’ª"

[[phrases]]
ivp = "ğ’«"

[[phrases]]
ivq = "ğ’¬"

[[phrases]]
ivr = "â„›"

[[phrases]]
ivs = "ğ’®"

[[phrases]]
ivt = "ğ’¯"

[[phrases]]
ivu = "ğ’°"

[[phrases]]
ivv = "ğ’±"

[[phrases]]
ivw = "ğ’²"

[[phrases]]
ivx = "ğ’³"

[[phrases]]
ivy = "ğ’´"

[[phrases]]
ivz = "ğ’µ"

[[phrases]]
iva = "ğ’¶"

[[phrases]]
ivb = "ğ’·"

[[phrases]]
ivc = "ğ’¸"

[[phrases]]
ivd = "ğ’¹"

[[phrases]]
ive = "â„¯"

[[phrases]]
ivf = "ğ’»"

[[phrases]]
ivg = "â„Š"

[[phrases]]
ivh = "ğ’½"

[[phrases]]
ivi = "ğ’¾"

[[phrases]]
ivj = "ğ’¿"

[[phrases]]
ivk = "ğ“€"

[[phrases]]
ivl = "ğ“"

[[phrases]]
ivm = "ğ“‚"

[[phrases]]
ivn = "ğ“ƒ"

[[phrases]]
ivo = "â„´"

[[phrases]]
ivp = "ğ“…"

[[phrases]]
ivq = "ğ“†"

[[phrases]]
ivr = "ğ“‡"

[[phrases]]
ivs = "ğ“ˆ"

[[phrases]]
ivt = "ğ“‰"

[[phrases]]
ivu = "ğ“Š"

[[phrases]]
ivv = "ğ“‹"

[[phrases]]
ivw = "ğ“Œ"

[[phrases]]
ivx = "ğ“"

[[phrases]]
ivy = "ğ“"

[[phrases]]
ivz = "ğ“"

[[phrases]]
ibp = "ğ˜½ğ™šğ™¨ğ™© ğ™‹ğ™§ğ™–ğ™˜ğ™©ğ™ğ™˜ğ™š"

[[phrases]]
ikb = "ğ™†ğ™£ğ™¤ğ™¬ğ™¡ğ™šğ™™ğ™œğ™š ğ˜½ğ™–ğ™¨ğ™š"
