# small chars
[[phrases]]
ixa = "áµƒ"

[[phrases]]
ixa = "â‚"

[[phrases]]
ixb = "áµ‡"

[[phrases]]
ixc = "á¶œ"

[[phrases]]
ixd = "áµˆ"

[[phrases]]
ixe = "â‚‘"

[[phrases]]
ixe = "áµ‰"

[[phrases]]
ixe = "â‚”"

[[phrases]]
ixf = "á¶ "

[[phrases]]
ixg = "áµ"

[[phrases]]
ixh = "Ê°"

[[phrases]]
ixh = "â‚•"

[[phrases]]
ixi = "áµ¢"

[[phrases]]
ixi = "â±"

[[phrases]]
ixi = "áµ"


[[phrases]]
ixj = "Ê²"

[[phrases]]
ixj = "â±¼"

[[phrases]]
ixk = "áµ"

[[phrases]]
ixk = "â‚–"

[[phrases]]
ixl = "Ë¡"

[[phrases]]
ixl = "â‚—"

[[phrases]]
ixm = "áµ"

[[phrases]]
ixm = "â‚˜"

[[phrases]]
ixn = "â¿"

[[phrases]]
ixn = "â‚™"

[[phrases]]
ixo = "áµ’"

[[phrases]]
ixo = "â‚’"

[[phrases]]
ixp = "áµ–"

[[phrases]]
ixp = "â‚š"

[[phrases]]
ixr = "Ê³"

[[phrases]]
ixr = "áµ£"

[[phrases]]
ixs = "Ë¢"

[[phrases]]
ixs = "â‚›"

[[phrases]]
ixt = "áµ—"

[[phrases]]
ixt = "â‚œ"

[[phrases]]
ixu = "áµ˜"

[[phrases]]
ixu = "áµ¤"

[[phrases]]
ixv = "áµ›"

[[phrases]]
ixv = "áµ¥"

[[phrases]]
ixw = "Ê·"

[[phrases]]
ixx = "Ë£"

[[phrases]]
ixx = "â‚“"

[[phrases]]
ixy = "Ê¸"

[[phrases]]
ixz = "á¶»"

# Tones
[[phrases]]
ixa = "Ä"

[[phrases]]
ixa = "Ã¡"

[[phrases]]
ixa = "Ç"

[[phrases]]
ixa = "Ã "

[[phrases]]
ixe = "Ä“"

[[phrases]]
ixe = "Ã©"

[[phrases]]
ixe = "Ä›"

[[phrases]]
ixe = "Ã¨"

[[phrases]]
ixi = "Ä«"

[[phrases]]
ixi = "Ã­"

[[phrases]]
ixi = "Ç"

[[phrases]]
ixi = "Ã¬"

[[phrases]]
ixo = "Å"

[[phrases]]
ixo = "Ã³"

[[phrases]]
ixo = "Ç’"

[[phrases]]
ixo = "Ã²"

[[phrases]]
ixu = "Å«"

[[phrases]]
ixu = "Ãº"

[[phrases]]
ixu = "Ç”"

[[phrases]]
ixu = "Ã¹"

# Mathematical Sans-Serif Bold Italic
[[phrases]]
ixa = "ğ˜¼"

[[phrases]]
ixb = "ğ˜½"

[[phrases]]
ixc = "ğ˜¾"

[[phrases]]
ixd = "ğ˜¿"

[[phrases]]
ixe = "ğ™€"

[[phrases]]
ixf = "ğ™"

[[phrases]]
ixg = "ğ™‚"

[[phrases]]
ixh = "ğ™ƒ"

[[phrases]]
ixi = "ğ™„"

[[phrases]]
ixj = "ğ™…"

[[phrases]]
ixk = "ğ™†"

[[phrases]]
ixl = "ğ™‡"

[[phrases]]
ixm = "ğ™ˆ"

[[phrases]]
ixn = "ğ™‰"

[[phrases]]
ixo = "ğ™Š"

[[phrases]]
ixp = "ğ™‹"

[[phrases]]
ixq = "ğ™Œ"

[[phrases]]
ixr = "ğ™"

[[phrases]]
ixs = "ğ™"

[[phrases]]
ixt = "ğ™"

[[phrases]]
ixu = "ğ™"

[[phrases]]
ixv = "ğ™‘"

[[phrases]]
ixw = "ğ™’"

[[phrases]]
ixx = "ğ™“"

[[phrases]]
ixy = "ğ™”"

[[phrases]]
ixz = "ğ™•"

[[phrases]]
ixa = "ğ™–"

[[phrases]]
ixb = "ğ™—"

[[phrases]]
ixc = "ğ™˜"

[[phrases]]
ixd = "ğ™™"

[[phrases]]
ixe = "ğ™š"

[[phrases]]
ixf = "ğ™›"

[[phrases]]
ixg = "ğ™œ"

[[phrases]]
ixh = "ğ™"

[[phrases]]
ixi = "ğ™"

[[phrases]]
ixj = "ğ™Ÿ"

[[phrases]]
ixk = "ğ™ "

[[phrases]]
ixl = "ğ™¡"

[[phrases]]
ixm = "ğ™¢"

[[phrases]]
ixn = "ğ™£"

[[phrases]]
ixo = "ğ™¤"

[[phrases]]
ixp = "ğ™¥"

[[phrases]]
ixq = "ğ™¦"

[[phrases]]
ixr = "ğ™§"

[[phrases]]
ixs = "ğ™¨"

[[phrases]]
ixt = "ğ™©"

[[phrases]]
ixu = "ğ™ª"

[[phrases]]
ixv = "ğ™«"

[[phrases]]
ixw = "ğ™¬"

[[phrases]]
ixx = "ğ™­"

[[phrases]]
ixy = "ğ™®"

[[phrases]]
ixz = "ğ™¯"

# Mathematical Script
[[phrases]]
ixa = "ğ’œ"

[[phrases]]
ixb = "â„¬"

[[phrases]]
ixc = "ğ’"

[[phrases]]
ixd = "ğ’Ÿ"

[[phrases]]
ixe = "â„°"

[[phrases]]
ixf = "â„±"

[[phrases]]
ixg = "ğ’¢"

[[phrases]]
ixh = "â„‹"

[[phrases]]
ixi = "â„"

[[phrases]]
ixj = "ğ’¥"

[[phrases]]
ixk = "ğ’¦"

[[phrases]]
ixl = "â„’"

[[phrases]]
ixm = "â„³"

[[phrases]]
ixn = "ğ’©"

[[phrases]]
ixo = "ğ’ª"

[[phrases]]
ixp = "ğ’«"

[[phrases]]
ixq = "ğ’¬"

[[phrases]]
ixr = "â„›"

[[phrases]]
ixs = "ğ’®"

[[phrases]]
ixt = "ğ’¯"

[[phrases]]
ixu = "ğ’°"

[[phrases]]
ixv = "ğ’±"

[[phrases]]
ixw = "ğ’²"

[[phrases]]
ixx = "ğ’³"

[[phrases]]
ixy = "ğ’´"

[[phrases]]
ixz = "ğ’µ"

[[phrases]]
ixa = "ğ’¶"

[[phrases]]
ixb = "ğ’·"

[[phrases]]
ixc = "ğ’¸"

[[phrases]]
ixd = "ğ’¹"

[[phrases]]
ixe = "â„¯"

[[phrases]]
ixf = "ğ’»"

[[phrases]]
ixg = "â„Š"

[[phrases]]
ixh = "ğ’½"

[[phrases]]
ixi = "ğ’¾"

[[phrases]]
ixj = "ğ’¿"

[[phrases]]
ixk = "ğ“€"

[[phrases]]
ixl = "ğ“"

[[phrases]]
ixm = "ğ“‚"

[[phrases]]
ixn = "ğ“ƒ"

[[phrases]]
ixo = "â„´"

[[phrases]]
ixp = "ğ“…"

[[phrases]]
ixq = "ğ“†"

[[phrases]]
ixr = "ğ“‡"

[[phrases]]
ixs = "ğ“ˆ"

[[phrases]]
ixt = "ğ“‰"

[[phrases]]
ixu = "ğ“Š"

[[phrases]]
ixv = "ğ“‹"

[[phrases]]
ixw = "ğ“Œ"

[[phrases]]
ixx = "ğ“"

[[phrases]]
ixy = "ğ“"

[[phrases]]
ixz = "ğ“"

[[phrases]]
ibestpractice = "ğ˜½ğ™šğ™¨ğ™© ğ™‹ğ™§ğ™–ğ™˜ğ™©ğ™ğ™˜ğ™š"

[[phrases]]
iknowledgebase = "ğ™†ğ™£ğ™¤ğ™¬ğ™¡ğ™šğ™™ğ™œğ™š ğ˜½ğ™–ğ™¨ğ™š"
