[[phrases]]
iup = "â†‘"

[[phrases]]
iup = "â–²"

[[phrases]]
iup = "â†–"

[[phrases]]
iup = "â†—"

[[phrases]]
iup = "â†•"

[[phrases]]
idown = "ğŸ”»"

[[phrases]]
idown = "â†“"

[[phrases]]
idown = "â–¼"

[[phrases]]
idown = "â†™"

[[phrases]]
idown = "â†˜"

[[phrases]]
idown = "â†•"

[[phrases]]
ileft = "â†"

[[phrases]]
ileft = "â—€"

[[phrases]]
ileft = "â†–"

[[phrases]]
ileft = "â†™"

[[phrases]]
ileft = "â†”"

[[phrases]]
iright = "â†’"

[[phrases]]
iright = "â–¶"

[[phrases]]
iright = "â†—"

[[phrases]]
iright = "â†˜"

[[phrases]]
iright = "â†”"

[[phrases]]
iround = "â†º"

[[phrases]]
iround = "â†»"
