[[phrases]]
ipro = "ğŸ‘"

[[phrases]]
icon = "ğŸ‘"

[[phrases]]
ilink = "ğŸ”—"

[[phrases]]
ilink = "â›“ï¸"  # â›“ U+26D3

[[phrases]]
ianchor = "âš“"

[[phrases]]
inote = "ğŸ—’ï¸"  # ğŸ—’ U+1F5D2

[[phrases]]
imemo = "ğŸ“"

[[phrases]]
ifolder = "ğŸ“"

[[phrases]]
ipage = "ğŸ“„"

[[phrases]]
imouse = "ğŸ–±ï¸"  # ğŸ–± U+1F5B1

[[phrases]]
istick = "ğŸ•¹ï¸"  # ğŸ•¹ U+1F579

[[phrases]]
igame = "ğŸ®"

[[phrases]]
ichestnut = "ğŸŒ°"

[[phrases]]
itag = "ğŸ·ï¸"  # ğŸ· U+1F3F7

[[phrases]]
ibookmark = "ğŸ”–"

[[phrases]]
ibox = "ğŸ”²"

[[phrases]]
ibox = "ğŸ”˜"

[[phrases]]
iok = "ğŸ†—"  # Squared Ok

[[phrases]]
iko = "ğŸˆ²"  # Prohibited

[[phrases]]
iok = "âœ”ï¸"  # White Heavy Check Mark 2010

[[phrases]]
iko = "âŒ"  # Cross Mark

[[phrases]]
iempty = "ğŸˆ³"

[[phrases]]
iplus = "â•"

[[phrases]]
iminus = "â–"

[[phrases]]
itimes = "âœ–ï¸"  # âœ– U+2716

[[phrases]]
idiv = "â—"

[[phrases]]
ifish = "ğŸ "  # Small

[[phrases]]
idolphin = "ğŸ¬"  # Medium

[[phrases]]
iwhale = "ğŸ³"  # Large

[[phrases]]
imale = "â™‚ï¸"  # â™‚ U+2642

[[phrases]]
ifemale = "â™€ï¸"  # â™€ U+2640
