# 모음
[[phrases]]
va = "ㅏ"

[[phrases]]
vae = "ㅐ"

[[phrases]]
vya = "ㅑ"

[[phrases]]
vyae = "ㅒ"

[[phrases]]
veo = "ㅓ"

[[phrases]]
ve = "ㅔ"

[[phrases]]
vyeo = "ㅕ"

[[phrases]]
vye = "ㅖ"

[[phrases]]
vo = "ㅗ"

[[phrases]]
vwa = "ㅘ"

[[phrases]]
vwae = "ㅙ"

[[phrases]]
voe = "ㅚ"

[[phrases]]
vyo = "ㅛ"

[[phrases]]
vu = "ㅜ"

[[phrases]]
vwo = "ㅝ"

[[phrases]]
vwe = "ㅞ"

[[phrases]]
vwi = "ㅟ"

[[phrases]]
vyu = "ㅠ"

[[phrases]]
veu = "ㅡ"

[[phrases]]
vui = "ㅢ"

[[phrases]]
vi = "ㅣ"


# 자음
[[phrases]]
vg = "ㄱ"  # g/k

[[phrases]]
vkk = "ㄲ"

[[phrases]]
vn = "ㄴ"

[[phrases]]
vd = "ㄷ"  # d/t

[[phrases]]
vtt = "ㄸ"

[[phrases]]
vr = "ㄹ"  # r/l

[[phrases]]
vm = "ㅁ"

[[phrases]]
vb = "ㅂ"  # b/p

[[phrases]]
vpp = "ㅃ"

[[phrases]]
vs = "ㅅ"

[[phrases]]
vss = "ㅆ"

[[phrases]]
vng = "ㅇ"

[[phrases]]
vj = "ㅈ"

[[phrases]]
vjj = "ㅉ"

[[phrases]]
vch = "ㅊ"

[[phrases]]
vk = "ㅋ"

[[phrases]]
vt = "ㅌ"

[[phrases]]
vp = "ㅍ"

[[phrases]]
vh = "ㅎ"
